name: amap_core_fluttify
description: Amap 'core' component, based on `fluttify` engine.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_core_fluttify
    pluginClass: AmapCoreFluttifyPlugin