name: amap_core_fluttify
description: An `Amap` Core Component, Powered By `Fluttify` Engine.
version: 0.2.3+324aaff
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_core_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_core_fluttify
    pluginClass: AmapCoreFluttifyPlugin
